### ISSUE TITLE
about building apk

### ISSUE THREAD

**Issue by volkanuchar** [ALIZE-Speaker-Recognition/android-alize#10]
hi. as told I downloaded core and lıa_ral as zip file.(maybe I understood wrong) then I copy and paste it to cpp with spro.  in SimpleSpkDetSystem class    <<System.loadLibrary("alize-native"); >> takes place. but I didnot download alize-naitive? and the methods like featurecounts,speakercounts,set option etc. all of them says "cannot resolve corrresponding JNI function". 

unfortunately I failed with it. can anybody help me about it.   my mail is volkanuchar@gmail.com

**Comment by RITCHIEHuang** [comment]
Hi, I have put all codes to the folder cpp and my project structure is like this:
![image](https://user-images.githubusercontent.com/16410627/38728901-c434699a-3f43-11e8-9436-6f11ee5f2a73.png)
But when I click on the Build->Build APKs , no thing happended.
I just want to know whether It's necessary for me to install all 3 library above in my PC.
And hopes your help.

**Comment by AhmadKhattak** [comment]
Hi, 

Check the following location in your android project, it should contain the android archive for ALIZE which you can then import as a module in your application projects (instructions from the readme)

<img width="566" alt="screen shot 2018-04-13 at 6 30 56 pm" src="https://user-images.githubusercontent.com/6959644/38737574-1e4a8a90-3f49-11e8-8ae4-3c08d6216fa5.png">

**Comment by RITCHIEHuang** [comment]
Really thanks @AhmadKhattak

**Comment by channae** [comment]
I get following exception when importing the aar. Any idea why?

```
com.intellij.openapi.externalSystem.model.ExternalSystemException: 
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:218)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.invokeGradleTasks(GradleTasksExecutorImpl.java:397)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.run(GradleTasksExecutorImpl.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Sunny-NEU** [comment]
i have fixed this problem already

**Comment by sriranjanr** [comment]
I am also getting the error Error:(313)  CMAKE_CXX_COMPILER not set, after EnableLanguage . How do I solve this error?

**Comment by sriranjanr** [comment]
How do I generate an APK or build an application out of this. A sample project to use this library/module would be helpful
