### ISSUE TITLE
Crashing with "UBM not found" when executing alizeSystem.createSpeakerModel(userName);

### ISSUE THREAD

**Issue by channae** [ALIZE-Speaker-Recognition/android-alize#17]
Stack-trace

```
04-17 14:29:31.216 5546-5546/com.example.channa.poc_alize W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
04-17 14:29:31.253 5546-5546/com.example.channa.poc_alize W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
04-17 14:29:31.253 5546-5546/com.example.channa.poc_alize W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
04-17 14:29:33.184 5546-5546/com.example.channa.poc_alize I/System.out: content://com.android.externalstorage.documents/document/primary%3AAudioClipsForSpeakerRecognition%2F1%2Fspeaker_1.wav
04-17 14:29:34.155 5546-5546/com.example.channa.poc_alize W/System.err: AlizeSpkRec.AlizeException: [ Exception 0x7c4ca25480 ]
      message   = "UBM not found"
      source file = /Users/channa/Documents/Projects/Work/Sample Projects/android-alize/alize/src/main/cpp/LIA_RAL/LIA_SpkDet/SimpleSpkDetSystem/src/SimpleSpkDetSystem.cpp
      line number = 869
        at AlizeSpkRec.SimpleSpkDetSystem.createSpeakerModel(Native Method)
        at com.example.channa.poc_alize.SpeakerRecognition.trainSpeakerModel(SpeakerRecognition.java:40)
        at com.example.channa.poc_alize.MainActivity.onActivityResult(MainActivity.java:97)
        at android.app.Activity.dispatchActivityResult(Activity.java:7226)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-17 14:29:34.182 5546-5586/com.example.channa.poc_alize D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
04-17 14:29:34.183 5546-5546/com.example.channa.poc_alize D/ViewRootImpl@52672bd[MainActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
    MSG_WINDOW_FOCUS_CHANGED 1
```

**Comment by channae** [comment]
I further debugged seems like following getIndexOfId method in MixtureDict.cpp is returning -1 

```
long D::getIndexOfId(const String& id) const
{
  /*for (unsigned long i=0; i<_vect.size(); i++)
    if (getMixture(i).getId() == id)
      return (long)i;
  return -1;*/
  std::map<String, unsigned long>::const_iterator it = _map.find(id);
  if (it != _map.end())
    return it->second;
  return -1;
}
```
